# COLLECTIONS
list = [1,2,3,4,5]

# list properties
print(len(list))  # length of the list
print(list.index(3))  # index of element 3
list.append(6)  # add element to the end
print(list)
list.remove(3)  # remove element 3
print(list)

# List Features
# ✔ Ordered
# ✔ Mutable (change ho sakti hai)
# ✔ Duplicate allow
# ✔ Different data types allow


# indexing,slicing,append,insert,extend,remove,pop,clear,sort,sort(reverse=true),count,index, copy
print("mohsin raza")